<?php
 $aik =  array (
  'sitename' => '菲戈全网解析',
  'pcdomain' => 'http://127.0.0.1',
  'title' => '菲戈VIP视频全网解析———菲戈互动分享',
  'keywords' => '优酷VIP解析,爱奇艺VIP解析,腾讯VIP解析,乐视VIP解析,芒果VIP解析,全网视频解析,VIP在线解析,视频VIP在线解析,VIP视频在线解析',
  'description' => '本站为广大网友提供优酷VIP解析，爱奇艺VIP解析，腾讯VIP解析，乐视VIP解析，芒果VIP解析等解析服务，让你省去购买视频VIP费用，欢迎大家收藏本站，并将它介绍给您的朋友！',
  'gonggao' => '<p>若视频播放异常或时长不对，请尝试【更换线路】或【刷新】即可解决！毕竟每条线路破解各个视频网站的变态封锁技术不一样~~~</p><p>如有线路不行，请把网页拉倒最下方，发邮件给站长，电脑端上体验最佳，手机端容易出现线路商的广告服务</p>',
  'maurl' => 'http://v.youku.com/v_show/id_XMTI4NTY3MTY1Mg==.html',
  'jiekou1name' => '线路一',
  'jiekou1' => 'http://api.wlzhan.com/sudu/?url=',
  'jiekou2name' => '线路二',
  'jiekou2' => 'http://000o.cc/jx/yk.php?url=',
  'jiekou3name' => '线路三',
  'jiekou3' => 'http://jx.maoyun.tv/index.php?id=',
  'jiekou4name' => '线路四',
  'jiekou4' => 'https://api.daidaitv.com/index/?url=',
  'jiekou5name' => '线路五',
  'jiekou5' => 'http://api.xfsub.com/index.php?url=',
  'jiekou6name' => '线路六',
  'jiekou6' => 'http://api.662820.com/xnflv/index.php?url=',
  'jiekou7name' => '线路七',
  'jiekou7' => 'http://vip.jlsprh.com/index.php?url=',
  'jiekou8name' => '线路八',
  'jiekou8' => 'http://jiexi.071811.cc/jx2.php?url=',
  'jiekou9name' => '测试线',
  'jiekou9' => 'http://aikan-tv.com/?url=',
  'jiekou10name' => '待添加',
  'jiekou10' => '',
  'topnav' => '',
  'foot' => '本站提供的最新电影和电视剧资源均系收集于各大视频网站,本站只提供web页面服务,并不提供影片资源存储,也不参与录制、上传。',
  'tongji' => '',
  'admin_email' => '283854469@qq.com',
);
?>